# Generated by Django 4.1.3 on 2022-12-25 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_autor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='autor',
            new_name='author',
        ),
    ]
